// <auto-generated />
using System;
using Asandului_Oana_Maria_Insurance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asandului_Oana_Maria_Insurance.Migrations
{
    [DbContext(typeof(InsuranceContext))]
    partial class InsuranceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Claim", b =>
                {
                    b.Property<int>("ClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PolicyID")
                        .HasColumnType("int");

                    b.HasKey("ClaimID");

                    b.HasIndex("PolicyID");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PolicyID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("PolicyID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Policy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyID"));

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProviderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PolicyID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProviderID");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Provider", b =>
                {
                    b.Property<int>("ProviderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderID");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Claim", b =>
                {
                    b.HasOne("Asandului_Oana_Maria_Insurance.Models.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyID");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Payment", b =>
                {
                    b.HasOne("Asandului_Oana_Maria_Insurance.Models.Policy", "Policy")
                        .WithMany("Payments")
                        .HasForeignKey("PolicyID");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Policy", b =>
                {
                    b.HasOne("Asandului_Oana_Maria_Insurance.Models.Customer", "Customer")
                        .WithMany("Policies")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Asandului_Oana_Maria_Insurance.Models.Provider", "Provider")
                        .WithMany("Policies")
                        .HasForeignKey("ProviderID");

                    b.Navigation("Customer");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Customer", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Asandului_Oana_Maria_Insurance.Models.Provider", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
